AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Lambda
      StageName: dev

  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/Lambda-0.0.1-SNAPSHOT.jar
      Handler: com.example.lambda.handler.ApiGatewayHandler
      Runtime: java8
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /path
            Method: post
            RestApiId:
              Ref: RestApi
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
